// Automation inventory categorized by product
// Synced with docs/AUTOMATION-LANDSCAPE.md

export type AutomationStatus = 'active' | 'disabled' | 'ready' | 'needs-migration' | 'needs-review'
export type AutomationType = 'app-cron' | 'agent-cron' | 'webhook' | 'heartbeat'

export interface AutomationJob {
  id: string
  name: string
  product: 'MyJunto' | 'Clawstreet' | 'Portfolio' | 'Marketing' | 'System'
  type: AutomationType
  usesAgent: boolean
  status: AutomationStatus
  schedule?: string
  description: string
  costPerDay?: number
  recommendation?: string
  cronId?: string // Actual clawdbot cron job ID if exists
}

export const automationInventory: AutomationJob[] = [
  // ===== MYJUNTO =====
  {
    id: 'myjunto-research-webhook',
    name: 'Research Requests (Push)',
    product: 'MyJunto',
    type: 'webhook',
    usesAgent: true,
    status: 'active',
    description: 'User submits research → instant webhook → Scout spawn',
    costPerDay: 0.25,
    recommendation: '✅ Keep - Replaced expensive polling ($18/day → $0.25/day)',
  },
  {
    id: 'myjunto-research-polling',
    name: 'Research Queue (Poll)',
    product: 'MyJunto',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '*/15 * * * *',
    description: 'Poll for pending research requests every 15 min',
    costPerDay: 0,
    recommendation: '❌ Delete - Replaced by push webhooks',
    cronId: '326377ee-8934-4202-9fb3-dc7e7086e1b7',
  },
  {
    id: 'myjunto-tweet-fetch',
    name: 'Tweet Fetch (xAI)',
    product: 'MyJunto',
    type: 'agent-cron',
    usesAgent: false,
    status: 'disabled',
    schedule: '0 12 * * *',
    description: 'Fetch tweets via xAI Grok for watchlist',
    costPerDay: 0,
    recommendation: '🟢 Re-enable - Powers newsletters (should be app-level)',
    cronId: '4b2f80cf-7b43-48b8-94c7-bbd9ebadd140',
  },

  // ===== CLAWSTREET =====
  {
    id: 'clawstreet-price-refresh',
    name: 'Price Refresh',
    product: 'Clawstreet',
    type: 'app-cron',
    usesAgent: false,
    status: 'active',
    schedule: '*/5 * * * *',
    description: 'Fetch live prices every 5 min (Yahoo + CoinGecko)',
    costPerDay: 0,
    recommendation: '✅ Keep - App-level, no agent',
  },
  {
    id: 'clawstreet-rps-timeout',
    name: 'RPS Timeout Enforcement',
    product: 'Clawstreet',
    type: 'app-cron',
    usesAgent: false,
    status: 'active',
    schedule: '*/2 * * * *',
    description: 'Auto-forfeit expired games',
    costPerDay: 0,
    recommendation: '✅ Keep - App-level, no agent',
  },
  {
    id: 'clawstreet-eod-snapshot',
    name: 'EOD Balance Snapshot',
    product: 'Clawstreet',
    type: 'app-cron',
    usesAgent: false,
    status: 'active',
    schedule: '0 2 * * *',
    description: 'Record daily balance history for all agents',
    costPerDay: 0,
    recommendation: '✅ Keep - App-level, no agent',
  },
  {
    id: 'clawstreet-agent-trading',
    name: 'Agent Trading',
    product: 'Clawstreet',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 15,20 * * 1-5',
    description: 'Make real trades for MomentumBot, Contrarian, RandomWalker',
    costPerDay: 0,
    recommendation: '⚠️ Needs approval - REAL MONEY trades',
    cronId: '96d4cbc1-dd72-407b-92b6-b5730141f547',
  },
  {
    id: 'clawstreet-lobs-backup',
    name: 'LOBS History (Backup)',
    product: 'Clawstreet',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '15 2 * * *',
    description: 'Backup balance snapshot (redundant with app-level)',
    costPerDay: 0,
    recommendation: '❌ Delete - Redundant with app-level EOD snapshot',
    cronId: '2582757e-7d0c-4fdf-9c67-43aa888c2265',
  },

  // ===== PORTFOLIO =====
  {
    id: 'portfolio-daily-report',
    name: 'Daily Portfolio Report',
    product: 'Portfolio',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 14 * * 1-5',
    description: 'Generate briefing with movers, options, interpretation',
    costPerDay: 0.5,
    recommendation: '🟢 Re-enable - Requires agent for interpretation',
    cronId: '7d989f5b-ad20-4cd2-a4cb-e579298fcfa6',
  },
  {
    id: 'portfolio-hourly-refresh',
    name: 'Hourly Price Refresh',
    product: 'Portfolio',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '30 14-20 * * 1-5',
    description: 'Update portfolio prices during market hours',
    costPerDay: 0,
    recommendation: '🔴 Migrate to app-level - Rote task, no agent needed',
    cronId: '6ce4a504-d4b7-44d8-ad14-1de18d4ed5ab',
  },
  {
    id: 'portfolio-market-close',
    name: 'Market Close Refresh',
    product: 'Portfolio',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 21 * * 1-5',
    description: 'Capture EOD prices',
    costPerDay: 0,
    recommendation: '🔴 Migrate to app-level - Rote task, no agent needed',
    cronId: '465511ab-dc92-4620-9867-5440530c61ea',
  },
  {
    id: 'portfolio-base-gas',
    name: 'Base Gas Check',
    product: 'Portfolio',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 14 * * *',
    description: 'Alert if Base deployer wallet < 0.002 ETH',
    costPerDay: 0,
    recommendation: '🔴 Migrate to app-level - Simple health check',
    cronId: 'e3ca97f6-20e7-432d-842f-b9799cd24b38',
  },

  // ===== MARKETING =====
  {
    id: 'marketing-mark-checkin',
    name: 'Mark Marketing Check-in',
    product: 'Marketing',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 */4 * * *',
    description: 'Draft tweets, post to Discord (every 4 hours)',
    costPerDay: 0,
    recommendation: '🟡 Review - Reduce to daily or disable',
    cronId: '71ac1eaa-f735-4849-9bc2-6860e19108ef',
  },
  {
    id: 'marketing-reply-guy',
    name: 'Mark Reply-Guy Scan',
    product: 'Marketing',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 15,18,21 * * *',
    description: 'Find Twitter reply opportunities (3x daily)',
    costPerDay: 0,
    recommendation: '❌ Delete - Not functional, needs setup work',
    cronId: '1d0d9c85-732c-4d5b-acd9-ebb1a68bb0c3',
  },
  {
    id: 'marketing-content-drafts',
    name: 'Content Drafts Reminder',
    product: 'Marketing',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 16 * * 1-5',
    description: 'Auto-draft tweet if Jon hasn\'t posted',
    costPerDay: 0,
    recommendation: '🟡 Review - Has this been useful?',
    cronId: 'ae54b68c-b108-4253-97f0-3f65b82ad6d9',
  },

  // ===== SYSTEM =====
  {
    id: 'system-heartbeat',
    name: 'Heartbeat (Flag-Based)',
    product: 'System',
    type: 'heartbeat',
    usesAgent: true,
    status: 'disabled',
    schedule: 'Every 30-60 min',
    description: 'Batch periodic checks (MyJunto, Trollbox, Kanban)',
    costPerDay: 2.0,
    recommendation: '🟢 Re-enable at 60min - Minimal flag checks, lazy load context',
  },
  {
    id: 'system-kanban',
    name: 'Kanban Task Pickup',
    product: 'System',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0,30 * * * *',
    description: 'Pick up ready tasks, spawn sub-agents',
    costPerDay: 0,
    recommendation: '🔄 Moved to heartbeat - Will be checked by flag-based heartbeat',
    cronId: 'd51f2b84-917c-4158-adcb-78a6ca169d0c',
  },
  {
    id: 'system-trollbox',
    name: 'Trollbox Check',
    product: 'System',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 * * * *',
    description: 'Check Clawstreet trollbox, respond as Jai-Alpha',
    costPerDay: 0,
    recommendation: '🔄 Moved to heartbeat - Will be checked by flag-based heartbeat',
    cronId: '5226e776-175a-4021-b56e-2dee4a513989',
  },
  {
    id: 'system-scout-retro',
    name: 'Scout Monthly Retrospective',
    product: 'System',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 14 1 * *',
    description: 'Performance review of research reports (monthly)',
    costPerDay: 0.03,
    recommendation: '🟢 Re-enable - Valuable monthly analysis',
    cronId: 'c0325e2e-d130-47c2-a955-3dac9d59a5e1',
  },
  {
    id: 'system-github-reminder',
    name: 'GitHub Token Reminder',
    product: 'System',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 14 27 4 *',
    description: 'Remind about token expiry (April 27)',
    costPerDay: 0,
    recommendation: '🟢 Keep - One-time reminder',
    cronId: 'b404c2ab-340e-4832-883d-7679e05bded1',
  },
  {
    id: 'system-dk-checkin',
    name: 'DK Compact State Check-in',
    product: 'System',
    type: 'agent-cron',
    usesAgent: true,
    status: 'disabled',
    schedule: '0 */6 * * *',
    description: 'Spawn DK sub-agent for Compact State contrib',
    costPerDay: 0,
    recommendation: '🟡 Review - Value unclear',
    cronId: '1fd2e6b9-beb1-496d-a1ea-8b7d5926c55a',
  },
]

// Summary stats
export const stats = {
  total: automationInventory.length,
  active: automationInventory.filter(j => j.status === 'active').length,
  appLevel: automationInventory.filter(j => !j.usesAgent).length,
  agentBased: automationInventory.filter(j => j.usesAgent).length,
  totalCostPerDay: automationInventory.reduce((sum, j) => sum + (j.costPerDay || 0), 0),
}

// Group by product
export const byProduct = {
  MyJunto: automationInventory.filter(j => j.product === 'MyJunto'),
  Clawstreet: automationInventory.filter(j => j.product === 'Clawstreet'),
  Portfolio: automationInventory.filter(j => j.product === 'Portfolio'),
  Marketing: automationInventory.filter(j => j.product === 'Marketing'),
  System: automationInventory.filter(j => j.product === 'System'),
}
